name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # Run Cosmos DB Emulator and Test
      # See https://github.com/Azure/cosmosdb-emulator-recipes/blob/main/github-actions/main.yml#L50
      - name: Start emulator
        id: run_emulator
        run: |
          set -e
          MAX_RETRIES=5
          SUCCESS=false
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt #$i"

            container_name=cosmosdb-emulator-$i

            docker run \
              --publish 8081:8081 \
              --publish 10250-10255:10250-10255 \
              --detach \
              --name=$container_name \
              --interactive \
              --tty \
              mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

            echo "Waiting for Emulator to Start"
            sleep 90  # Increased startup timeout

            echo "Getting Emulator Logs"
            docker logs $container_name

            echo "Checking Emulator Logs for 'Started' Keyword"
            if docker logs $container_name | grep -q "Started"; then
              echo "Emulator started successfully."
              SUCCESS=true
              break
            else
              echo "Emulator failed to start on attempt #$i." >&2
              docker rm -f $container_name || true  # Ensure cleanup even in failure
              echo "Retrying..."
            fi
          done

          if [ "$SUCCESS" = false ]; then
            echo "Emulator failed to start after $MAX_RETRIES attempts." >&2
            echo "::error::Emulator failed to start after $MAX_RETRIES attempts."
            exit 1
          fi

      # Download and install Cosmos DB emulator certificate
      - name: Download and install Cosmos DB emulator certificate
        if: steps.run_emulator.outcome == 'success'
        run: |
          # Download the emulator certificate
          curl -k https://localhost:8081/_explorer/emulator.pem > ~/emulatorcert.crt
          
          # Install the emulator certificate
          sudo cp ~/emulatorcert.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates

          # Verify the installation
          ls -l /usr/local/share/ca-certificates/emulatorcert.crt
          ls -l /etc/ssl/certs/emulatorcert.pem  

      - name: Run tests
        run: pnpm test
        env:
          COSMOS_DB_ENDPOINT: https://localhost:8081
          COSMOS_DB_KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
          COSMOS_DB_DATABASE_NAME: better-auth-cosmosdb-adapter-test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Publish to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
